# this config file is for local development environment
cluster: 
  mode: static # the cluster can be either 'static' or 'dynamic'
  servers: # if the mode is 'dynamic', `servers` will be ignored
    - id: 1
      host: "localhost"
      http_port: 8080
      rpc_port: 1234
    - id: 2
      host: "localhost"
      http_port: 8081
      rpc_port: 1235
    - id: 3
      host: "localhost"
      http_port: 8082
      rpc_port: 1236
# timeout in miliseconds
min_election_timeout_ms: 12000
max_election_timeout_ms: 15000
min_heartbeat_timeout_ms: 2000
max_heartbeat_timeout_ms: 5000
data_folder: data/
state_machine_snapshot: false
client_session_duration: 2m
rpc_dial_timeout: 5s
rpc_request_timeout: 1s
rpc_reconnect_duration: 30s
observability:
  disabled: true
  trace_endpoint: 'localhost:4318'
  log_endpoint: 'localhost:3100'
  loki_push_url: 'http://localhost:3100/loki/api/v1/push'
