# this config file is for docker compose environment
cluster: 
  mode: static # the cluster can be either 'static' or 'dynamic'
  servers: # if the mode is 'dynamic', `servers` will be ignored
    - id: 1
      host: "raft-node-1.raft-cluster.local"
      http_port: 8080
      rpc_port: 1234
    - id: 2
      host: "raft-node-2.raft-cluster.local"
      http_port: 8080
      rpc_port: 1234
    - id: 3
      host: "raft-node-3.raft-cluster.local"
      http_port: 8080
      rpc_port: 1234
# timeout in milliseconds
min_election_timeout: 12s
max_election_timeout: 15s
min_heartbeat_timeout: 2s
max_heartbeat_timeout: 5s
data_folder: data/
wal_size_limit: 512
log_length_limit: 5
client_session_duration: 2m
rpc_dial_timeout: 5s
rpc_request_timeout: 1s
rpc_reconnect_duration: 30s
observability:
  disabled: true
  trace_endpoint: 'tempo:4318'
  log_endpoint: 'loki:3100'
  loki_push_url: 'http://loki:3100/loki/api/v1/push'
