# this config file is for Kubernetes environment
cluster: 
  mode: static # the cluster can be either 'static' or 'dynamic'
  servers: # if the mode is 'dynamic', `servers` will be ignored
    - id: 1
      host: "raft-node-0.raft-cluster.raft-go.svc.cluster.local"
      http_port: 8080
      rpc_port: 1234
    - id: 2
      host: "raft-node-1.raft-cluster.raft-go.svc.cluster.local"
      http_port: 8080
      rpc_port: 1234
    - id: 3
      host: "raft-node-2.raft-cluster.raft-go.svc.cluster.local"
      http_port: 8080
      rpc_port: 1234
# timeout in miliseconds
min_election_timeout_ms: 12000
max_election_timeout_ms: 15000
min_heartbeat_timeout_ms: 2000
max_heartbeat_timeout_ms: 5000
data_folder: data/
state_machine_snapshot: false
observability:
  disabled: true
  trace_endpoint: 'tempo:4318'
  log_endpoint: 'loki:3100'
  loki_push_url: 'http://loki:3100/loki/api/v1/push'