cluster:
  mode: dynamic # the cluster can be either 'static' or 'dynamic'
# timeout in miliseconds
min_election_timeout_ms: 150
max_election_timeout_ms: 300
min_heartbeat_timeout_ms: 1
max_heartbeat_timeout_ms: 20
data_folder: data/
state_machine_snapshot: false