cluster:
  mode: dynamic # the cluster can be either 'static' or 'dynamic'
# timeout in miliseconds
min_election_timeout_ms: 150
max_election_timeout_ms: 300
min_heartbeat_timeout_ms: 1
max_heartbeat_timeout_ms: 20
data_folder: data/
state_machine_snapshot: true
wal_size_limit: 10240
log_length_limit: 100
client_session_duration: 2m
rpc_dial_timeout: 300ms
rpc_request_timeout: 150ms
rpc_reconnect_duration: 300ms
observability:
  disabled: true
  trace_endpoint: 'localhost:4318'
  log_endpoint: 'localhost:3100'
  loki_push_url: 'http://localhost:3100/loki/api/v1/push'