# this config file is for local development environment
raft_core:
  cluster: 
    mode: static # the cluster can be either 'static' or 'dynamic'
    servers: # if the mode is 'dynamic', `servers` will be ignored
      - id: 1
        host: "localhost"
        http_port: 8080
        rpc_port: 1234
      - id: 2
        host: "localhost"
        http_port: 8081
        rpc_port: 1235
      - id: 3
        host: "localhost"
        http_port: 8082
        rpc_port: 1236
      - id: 4
        host: "localhost"
        http_port: 8083
        rpc_port: 1237
      - id: 5
        host: "localhost"
        http_port: 8084
        rpc_port: 1238
  # timeout in milliseconds
  min_election_timeout: 150ms
  max_election_timeout: 300ms
  min_heartbeat_timeout: 1ms
  max_heartbeat_timeout: 20ms
  data_folder: data/
  state_machine_snapshot: true
  wal_size_limit: 10240
  log_length_limit: 100
  rpc_dial_timeout: 200ms
  rpc_request_timeout: 150ms
  rpc_reconnect_duration: 300ms
  snapshot_chunk_size: 100
  cluster_time_commit_max_duration: 30s
  http_client_request_max_timeout: 60m
extension:
  state_machine_history_capacity: 10
  state_machine_btree_degree: 32
  http_client_max_wait_timeout: 60m
observability:
  disabled: true
  trace_endpoint: 'localhost:4318'
  log_endpoint: 'localhost:3100'
  loki_push_url: 'http://localhost:3100/loki/api/v1/push'
