# this config file is for docker compose environment
cluster: 
  mode: static # the cluster can be either 'static' or 'dynamic'
  servers: # if the mode is 'dynamic', `servers` will be ignored
    - id: 1
      host: "raft-node-1.raft-cluster.local"
      http_port: 8080
      rpc_port: 1234
    - id: 2
      host: "raft-node-2.raft-cluster.local"
      http_port: 8080
      rpc_port: 1234
    - id: 3
      host: "raft-node-3.raft-cluster.local"
      http_port: 8080
      rpc_port: 1234
# timeout in milliseconds
min_election_timeout: 12s
max_election_timeout: 15s
min_heartbeat_timeout: 2s
max_heartbeat_timeout: 5s
data_folder: data/
state_machine_snapshot: true
wal_size_limit: 10240
log_length_limit: 100
client_session_duration: 2m
rpc_dial_timeout: 200ms
rpc_request_timeout: 150ms
rpc_reconnect_duration: 300ms
observability:
  disabled: false
  trace_endpoint: 'tempo:4318'
  log_endpoint: 'loki:3100'
  loki_push_url: 'http://loki:3100/loki/api/v1/push'
